<?php

use Faker\Generator as Faker;

$factory->define(App\Contact::class, function (Faker $faker) {
    return [
        'affiliateCode' => $faker->ein,
        'prefix' => $faker->title, 
        'lastname' => $faker->firstName(),
        'firstname' => $faker->lastName(),
        'middleinit' => $faker->firstName(),
        'nickname' => $faker->firstName(),
        'gender' => $faker->randomElements(['male', 'female'])[0],
        'birthdate' => date('Y'),
        'spouse' => $faker->name,
        'children' => 1,
        'hobbies' => 'table tennis',
        'nationality' => $faker->countryCode,
        'specialization' => $faker->text(100),
        'officeMobile' => $faker->text,
        'homeMobile' => $faker->text,
        'officePhone' => $faker->text,
        'homePhone' => $faker->text,
        'officeEmail' => $faker->email,
        'homeEmail' => $faker->freeEmail,
        'homeAddress' => $faker->address,
        'homeCountry' => $faker->country,
        'officeAddress' => $faker->address,
        'officeCountry' => $faker->country,
        'homeZipCode' => $faker->postCode,
        'officeZipCode' => $faker->postCode,
        'officeFax' => $faker->text,
        'homeFax' => $faker->text,
        'officeCountryCode' => $faker->countryCode,
        'homeCountryCode' => $faker->countryCode,
        'officeAreaCode' => $faker->areaCode,
        'homeAreaCode' => $faker->areaCode,
        'status' => $faker->randomElements(['single', 'married'])[0],
        'civilStat' => $faker->randomElements(['single', 'married'])[0],
        'position' => $faker->text(20),
        'dept' => $faker->text(20),
        'company' => $faker->company,
        'others' => $faker->text,
        'sector' => $faker->company,
        'contactMeans' => $faker->areaCode,
        'mailMeans' => $faker->email,
        'rank' => 1,
        'suffix' => $faker->suffix,
    ];
});
